export const USER_ADDRESS_INFO = {
  status: 'success',
  country: 'Poland',
  countryCode: 'PL',
  region: '02',
  regionName: 'Lower Silesia',
  city: 'Wroclaw',
  zip: '50-019',
  lat: 51.1043,
  lon: 17.0335,
  timezone: 'Europe/Warsaw',
  isp: 'TK Telekom sp. z o.o',
  org: 'WROCNET M.Konstantynowicz T.Jozefowicz Sp. j.',
  as: 'AS20960 TK Telekom sp. z o.o.',
  query: '88.199.123.71',
};

export const EXAMPLE_RESPONSES = [
  {
    status: 'success',
    country: 'Poland',
    countryCode: 'PL',
    region: '02',
    regionName: 'Lower Silesia',
    city: 'Wroclaw',
    zip: '50-088',
    lat: 51.0984,
    lon: 17.031,
    timezone: 'Europe/Warsaw',
    isp: 'OVH ISP',
    org: 'OVH Sp. z o. o',
    as: 'AS16276 OVH SAS',
    query: '178.33.51.175',
  },
  {
    status: 'success',
    country: 'Canada',
    countryCode: 'CA',
    region: 'ON',
    regionName: 'Ontario',
    city: 'Toronto',
    zip: 'M5A',
    lat: 43.6532,
    lon: -79.3832,
    timezone: 'America/Toronto',
    isp: 'Cloudflare, Inc.',
    org: 'Cloudflare, Inc.',
    as: 'AS13335 Cloudflare, Inc.',
    query: '2606:4700:3031::6815:2170',
  },
  {
    status: 'success',
    country: 'United States',
    countryCode: 'US',
    region: 'NY',
    regionName: 'New York',
    city: 'New York',
    zip: '10123',
    lat: 40.7128,
    lon: -74.006,
    timezone: 'America/New_York',
    isp: 'Google LLC',
    org: 'Google LLC',
    as: 'AS15169 Google LLC',
    query: '172.217.12.142',
  },
  {
    status: 'success',
    country: 'United States',
    countryCode: 'US',
    region: 'MI',
    regionName: 'Michigan',
    city: 'Dearborn',
    zip: '48121',
    lat: 42.3223,
    lon: -83.1763,
    timezone: 'America/Detroit',
    isp: 'Ford Motor Company',
    org: 'Ford Motor Company',
    as: '',
    query: '2001:0:130f::9c0:876a:130b',
  },
  {
    status: 'success',
    country: 'United States',
    countryCode: 'US',
    region: 'CA',
    regionName: 'California',
    city: 'Mountain View',
    zip: '94043',
    lat: 37.422,
    lon: -122.084,
    timezone: 'America/Los_Angeles',
    isp: 'Google LLC',
    org: 'Google LLC',
    as: 'AS15169 Google LLC',
    query: '172.253.122.136',
  },
  {
    status: 'success',
    country: 'United States',
    countryCode: 'US',
    region: 'CA',
    regionName: 'California',
    city: 'San Francisco',
    zip: '94107',
    lat: 37.7823,
    lon: -122.391,
    timezone: 'America/Los_Angeles',
    isp: 'GitHub, Inc.',
    org: 'GitHub, Inc.',
    as: 'AS36459 GitHub, Inc.',
    query: '140.82.112.3',
  },
  {
    status: 'success',
    country: 'France',
    countryCode: 'FR',
    region: 'IDF',
    regionName: 'Île-de-France',
    city: 'Paris',
    zip: '75008',
    lat: 48.8714,
    lon: 2.32141,
    timezone: 'Europe/Paris',
    isp: 'Online S.A.S.',
    org: 'ONLINE',
    as: 'AS12876 SCALEWAY S.A.S.',
    query: '212.129.51.63',
  },
  {
    status: 'success',
    country: 'United States',
    countryCode: 'US',
    region: 'CA',
    regionName: 'California',
    city: 'Los Angeles',
    zip: '90060',
    lat: 34.0544,
    lon: -118.2441,
    timezone: 'America/Los_Angeles',
    isp: 'Facebook, Inc.',
    org: 'Meta Platforms Ireland Limited',
    as: 'AS32934 Facebook, Inc.',
    query: '31.13.70.36',
  },
  {
    status: 'success',
    country: 'United States',
    countryCode: 'US',
    region: 'CA',
    regionName: 'California',
    city: 'San Francisco',
    zip: '94103',
    lat: 37.7768,
    lon: -122.416,
    timezone: 'America/Los_Angeles',
    isp: 'Twitter Inc.',
    org: 'Twitter Inc',
    as: 'AS13414 Twitter Inc.',
    query: '104.244.42.1',
  },
  {
    status: 'success',
    country: 'Canada',
    countryCode: 'CA',
    region: 'ON',
    regionName: 'Ontario',
    city: 'Toronto',
    zip: 'M5A',
    lat: 43.6532,
    lon: -79.3832,
    timezone: 'America/Toronto',
    isp: 'Cloudflare, Inc.',
    org: 'Cloudflare, Inc.',
    as: 'AS13335 Cloudflare, Inc.',
    query: '172.67.70.227',
  },
];
